version: "3.6"
services:
  mysql:
    image: mysql:8.0.25
    container_name: mysql
    privileged: true
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysql-files:/var/lib/mysql-files
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=voice9
    network_mode: "bridge"

  redis:
    image: redis:7.0.4
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
    command: --requirepass '123456'
    network_mode: "bridge"

  rabbitmq:
    image: rabbitmq:3.10.12-management
    container_name: rabbitmq
    privileged: true
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - /etc/localtime:/etc/localtime
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=voice9
    network_mode: "bridge"

  minio:
    image: minio/minio:RELEASE.2022-01-25T19-56-04Z
    container_name: minio
    privileged: true
    restart: always
    ports:
      - "9000:9000"
      - "9100:9100"
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio/
      - /etc/localtime:/etc/localtime
    environment:
      MINIO_ACCESS_KEY: 'admin'
      MINIO_SECRET_KEY: 'voice9_123456'
      MINIO_PROMETHEUS_AUTH_TYPE: 'public'
    command: server --console-address ':9100' /data
    network_mode: "bridge"

  cc-api:
    image: cc-api:1.3.0
    container_name: cc-api
    restart: always
    ports:
      - "7100:7100"
    volumes:
      - ./cc-api/conf:/webapps/conf
      - ./cc-api/logs:/webapps/logs
    environment:
      - JAVA_OPTS=-Xmn256m -Xmx1g -Xms1g
      - TZ=Asia/Shanghai
    network_mode: "bridge"

  fs-api:
    image: fs-api:1.3.0
    container_name: fs-api
    restart: always
    ports:
      - "7200:7200"
      - "7250:7250"
      - "7280:7280"
    volumes:
      - ./fs-api/conf:/webapps/conf
      - ./fs-api/logs:/webapps/logs
    environment:
      - JAVA_OPTS=-Xmn256m -Xmx1g -Xms1g
      - TZ=Asia/Shanghai
    network_mode: "bridge"

  cc-ivr:
    image: cc-ivr:1.3.0
    container_name: cc-ivr
    restart: always
    ports:
      - "7300:7300"
    volumes:
      - ./cc-ivr/conf:/webapps/conf
      - ./cc-ivr/logs:/webapps/logs
    environment:
      - JAVA_OPTS=-Xmn256m -Xmx1g -Xms1g
      - TZ=Asia/Shanghai
    network_mode: "bridge"

  freeswitch:
    image: registry.cn-hangzhou.aliyuncs.com/voice9_x86/freeswitch:1.1.0
    container_name: freeswitch
    restart: always
    tty: true
    volumes:
      - ./freeswitch/conf:/app/freeswitch/conf
      - ./freeswitch/log:/app/freeswitch/log
      - ./freeswitch/record:/app/freeswitch/record
      - ./freeswitch/storage:/app/freeswitch/storage
    network_mode: "host"
